---
- hosts: linux
  user: sysadmin
  become: yes
  gather_facts: no
  tasks:
   - name: Aplico medida de seguridad ssh
     ansible.builtin.lineinfile:
       path: /etc/ssh/sshd_config
       regexp: "{{ item.abuscar }}"
       line: " {{ item.reemplazo }} "
     loop:
       - { abuscar: '#PermitRootLogin ', reemplazo: 'PermitRootLogin no' }
       - { abuscar: '#AuthenticationMethods ', reemplazo: 'Authenticationmethods publickey' }
       - { abuscar: '#PubkeyAuthentication ', reemplazo: 'PubkeyAuthentication yes' }
     notify: Reinicio ssh

  handlers:
    - name: Reinicio ssh
      service:
        name: "{{ ssh_service }}"
        state: restarted
...
